#This function is used to plot the real tract FA profile. the
#data was generated by ExploreDTI softerware.

library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)


addCol <- function(df) {
  subj <- as.character(df$V1[1])
  eleList <- strsplit(subj, '_')
  ID <- eleList[[1]][3]
  Hemisphere <- eleList[[1]][2]
  Tract <- eleList[[1]][1]
  df$Point <- 1:nrow(df)
  df$ID <- rep(ID, nrow(df))
  df$Tract <- rep(Tract, nrow(df))
  df$Hemisphere <- rep(Hemisphere, nrow(df))
  df
}
calcFD <- function(df) {
  df_L <- filter(df, Hemisphere == 'L')
  df_R <- filter(df, Hemisphere == 'R')
  FDcalc(df_L, df_R)
}

FDcalc <- function(df1, df2) {
  FDvalue <- sum(abs(df1$FA-df2$FA))/nrow(df1)
}

filename <- choose.files()
FADt <- read.table(filename, sep = '\t')
df <- gather(FADt, 'Point', 'FA', 2:ncol(FADt))
df_new <- select(ddply(df, c('V1'), addCol), 
                 c(ID, Tract, Hemisphere, Point, FA))
p1 <- ggplot(df_new, aes(x = Point, y = FA))
p1 <- p1 + geom_line(aes(color = Hemisphere)) + 
  facet_wrap(~ID, nrow = 5)